### PR TITLE
may also return "Unknown" if no description was found

### PR DESCRIPTION
**Pull request by divinity76**
see

php -r 'const XML_NS_ERR_UNDEFINED_NAMESPACE = 201; var_dump(xml_error_string(XML_NS_ERR_UNDEFINED_NAMESPACE));' string(7) "Unknown"

### CODE REVIEW

**Comment by divinity76** [comment]
update: per https://github.com/php/php-src/blob/bbbe56eecc6ff6b3971ba4f924d51c9aa11955c5/ext/xml/xml.c#L1390 it always returns "Unknown" when not found; never null

(imo that shit should be fixed in the next major php version but oh well)

**Review by nielsdos — CHANGES_REQUESTED** [review]
This change isn't right.
If it's compiled with libexpat you can get a NULL value if there's no description: https://github.com/libexpat/libexpat/blob/bfd178c6350bbb46dbc71dae299a1d531468bf8a/expat/lib/xmlparse.c#L2415
Either our compat layer should be adapted, or we should add a NULL check for libexpat which translates the string to "Unknown". I think the former is the best one.

**Comment by divinity76** [comment]
adapting the compat layer sounds best to me too, but that would be a (small) breaking change 🤔

**Comment by nielsdos** [comment]
Yeah, although the compat layer is actually the default one so the impact may be larger...
As for wording: we don't use var_dump-style strings in the docs. You should use `<literal>Unknown</literal>`

**Review by nielsdos — APPROVED** [review]
Thanks!

**Pull request merged**
