### PR TITLE
Moved early algorithm description to warning block

### PR DESCRIPTION
**Pull request by mumumu**
image

### CODE REVIEW

**Comment by cmb69** [comment]
Thank you! I agree that this information should be more emphasized, but a `<warning>` might be too strong. Maybe use `<caution>` instead. @jimwins, @TimWolla, thoughts?

**Comment by TimWolla** [comment]
<caution> makes sense to me and matches the caution note for `rand()`: https://www.php.net/manual/en/function.rand

**Comment by jimwins** [comment]
Works for me, no strong opinion on warning vs. caution.

**Comment by mumumu** [comment]
OK. changed to `<caution>` on https://github.com/php/doc-en/pull/3635/commits/b4c7903b8bd3c0328f91d8bb6f0c779e9f59ede5.

**Review by cmb69 — APPROVED** [review]

**Pull request merged**
