### PR TITLE
Change reference from installation.problems to faq.installation

### PR DESCRIPTION
**Pull request by jimwins**
A chapter with three tiny sections is annoying.

### CODE REVIEW

**Comment by cmb69** [comment]
Makes sense to collapse this, but I'm not sure whether we should keep the info about the install mailing list. Apparently, nobody is responding there for a couple of years: https://news-web.php.net/php.install.

**Comment by jimwins** [comment]
Maybe it would be better to just remove this section entirely and link directly to faq.installation instead.

**Comment by Girgias** [comment]
If the section is removed, remember to first delete all the notes on these pages.

**Comment by Girgias** [comment]
I do think removing this and linking to the FAQ is better, as this section seems kinda pointless?

Not sure what I think about the "if you found a bug" thing, as it makes some sense to have this somewhere, but not in the installation section.

**Comment by jimwins** [comment]
Okay, removal it is. The stuff about bug reporting is already in the general FAQ. Requires a doc-base change because the section is in `manual.xml.in`.

**Comment by Girgias** [comment]
Could you split it in two commits? First change where the link points, merge this, update translations, then remove the page and update doc-base, seems like a more reliable course of action

**Comment by jimwins** [comment]
Sorry for the flapping, fixed this PR to just update the reference. Will submit another PR to remove.

**Review by Girgias — APPROVED** [review]

**Pull request merged**
