### PR TITLE
basic.xml: an indication of specific ways to create an instance of a …

### PR DESCRIPTION
**Pull request by mmalferov**
…class

It's hard to look for exactly which different ways of instantiation are discussed in the documentation

P. S. I probably specified through/by and a/the incorrectly, correct if necessary, please

### CODE REVIEW

**Comment by mmalferov** [comment]
> Note: Prior to PHP 7.1, the arguments are not evaluated if there is no constructor function defined.

What arguments are we talking about? If we are talking about class properties, maybe we should write this? Like that:

> Note: Prior to PHP 7.1, the **properties** are not evaluated if there is no constructor **method** defined.

**Comment by mmalferov** [comment]
> Note: Prior to PHP 7.1, the arguments are not evaluated if there is no constructor function defined.

An incomprehensible sentence. This is probably about the behavior of the code, an example of which I will give below. But the proposal does not disclose the behavior of the code prior to PHP 7.1.

```
<?php

class Foo
{
	// Prior to PHP 7.1, uncomment to get 1 in `echo $number` expression
	// public function __construct() {}
}

$number = 0;
new Foo(++$number); // The argument are not evaluated prior to PHP 7.1
echo $number; // 1, or 0 prior to PHP 7.1 without __construct() method or 1 with it

?>
```

**Comment by Girgias** [comment]
Are the comments really that useful? It might make more sense to split the example into 4 smaller different examples?

**Comment by mmalferov** [comment]
Mastodons like you don't need comments, experience allows you to understand everything the first time ;-) And beginners have to thoughtfully analyze every, line, of, code. The comment is at least visually separated by different ways of creating an instance of a class. I was asked: Where exactly in the example of 'a couple of ways'? And when I showed an example with comments, the student immediately understood what to pay attention to. I don't know why beginners have such difficulties. For example, they can reason like this: maybe `getNew()` is a built—in method of each PHP class and it is this method that creates an instance of the `Test` class? Stupid? Maybe. But if there were comments, there were no more questions. And it is unknown how quirky novice programmers can still reason. I'm sure the comments won't hurt.

These comments are just to say: here, here, here and here.

I wouldn't make four small examples out of one example, if only because then you won't have to describe the `Test` and `Child` classes four times :-)

**Pull request merged**
