### PR TITLE
Use standard DocBook tag for predefined variables

### PR DESCRIPTION
**Pull request by Girgias**
In conjunction with https://github.com/php/phd/pull/85

### CODE REVIEW

**Comment by Girgias** [comment]
@mumumu @saundefined I might run this as a ``[skip-revcheck]`` commit to first see if the indexing and search still behaves as expected.

Also, if I actually change all the ``<phpdoc:classref>`` it would mark the whole docs as outdated when it's not true. But I would make the changes on every single translation repo when this change happens.

**Comment by Girgias** [comment]
I'm actually testing this first on doc-fr and writing a shell script which does a bunch of sed commands to migrate this :')

**Comment by saundefined** [comment]
Can do without `[skip-revcheck]`, not many changes here,
thanks!

**Comment by Girgias** [comment]
> Can do without `[skip-revcheck]`, not many changes here, thanks!

Yeah but I can automate them and push them to translations without messing stuff up. Considering I need to change a lot of classes too :|

**Comment by Girgias** [comment]
Merged with skip revcheck already

**Pull request closed without merging**
