### PR TITLE
Fix spacing in mongodb.option.encryption.kmsProviders

### PR DESCRIPTION
**Pull request by jmikola**

### CODE REVIEW

**Review by cmb69 — APPROVED** [review]

**Comment by jmikola** [comment]
@cmb69 Will do! I actually opened this PR before reading all of https://externals.io/message/112642 about SVN karma being migrated to git.php.net. I assume that doesn't apply to GitHub perms, though.

In any event, I'll close this out and make the change directly once I get my docs Git environment setup.

**Comment by cmb69** [comment]
The karma should already been adjusted for Git, but you shouldn't commit to this Github mirror, but to git.php.net; see https://github.com/php/doc-base/blob/master/README.md for details.

**Comment by jmikola** [comment]
Merged in https://github.com/php/doc-en/commit/c47cd3156640f6fddbb20ed1c8b5c86a706f9b0e

**Comment by cmb69** [comment]
Tip: you could have added `Closes-GH312` to the commit message; that would have closed the respective PR right away.

**Pull request closed without merging**
