### PR TITLE
magic methods: improve __invoke documentation

### PR DESCRIPTION
**Pull request by houssemz**
I find that the documentation of magic methods is poor of practicals examples. In this PR I try do improve the documentation of `__invoke` method. Hope that will be accepted.

### CODE REVIEW

**Comment by houssemz** [comment]
@Girgias need a review, please :) thank you 🙏

**Comment by cmb69** [comment]
Thank you for the PR! I wonder whether this example would make more sense on the `usort()` page; there could be a link from the `__invoke()` documentation.

**Comment by houssemz** [comment]
@cmb69 yes ^^! it is related to both `__invoke ` and `usort `. But, I think it should be here (in the `__invoke` method documentation) because I find this one really poor and could cause confusion. When you arrive for the first time on PHP and you try to understand why we use `__invoke` you do not found a "real-world" example. Hope that is was convincing and clear :)

**Comment by houssemz** [comment]
Ping @cmb69 :)

**Comment by Crell** [comment]
I'm torn here.

1. Yes, we should have examples for the magic methods.
2. However, the current magic method page is stupidly huge.  It may be beneficial to split it up into several pages.
3. Adding long examples to the current page kinda just makes it worse.
4. But at the same time, this particular example does kinda make sense on the `usort` page instead... but that's not going to work for everything.  So we probably should *not* go down that route.  Whether that example is useful on the `usort` page on its own merits is a separate question.
5. I'm not sure if this is the best example for `__invoke()`, since I've never seen it used this way.  It certainly could be, though.

So... maybe we can commit this, and i a follow up see about spitting up the page?

**Comment by cmb69** [comment]
> 4\. Whether that example is useful on the `usort` page on its own merits is a separate question.

I think it is fitting there, because it shows how to use a configurable callable to do the comparisons.

> So... maybe we can commit this, and i a follow up see about spitting up the page?

This is also fine for me.

**Comment by houssemz** [comment]
IMHO, I am okay also with that we should separate this page because it is really huge (I will make some initiatives). 

I think also, that documentation should avoid us to search for examples somewhere else that's why I added what I called a real "word example".

But still, are you ok with this modification? Should I do any modification?

**Pull request merged**
