### PR TITLE
Fix "see also" for ReflectionFunction::__toString

### PR DESCRIPTION
**Pull request by WinterSilence**

### CODE REVIEW

**Comment by WinterSilence** [comment]
@kamil-tekiela no reason recoment deprecated/removed methods

**Comment by kamil-tekiela** [comment]
It's not a recommendation. It's a see also. If a new function is a replacement for a removed function then it's a good idea to mention what the old function was.

**Comment by WinterSilence** [comment]
@kamil-tekiela ok, roll back

**Review by kamil-tekiela — APPROVED** [review]
Thank you.

**Pull request merged**
