### PR TITLE
Fix GH-2156: stdClass is spelled in different cases: StdClass / stdclass

### PR DESCRIPTION
**Pull request by cmb69**
Not sure if this commit should be marked with `[skip-revcheck]`. @mumumu, @Girgias, @saundefined, what do you think?

### CODE REVIEW

**Comment by cmb69** [comment]
Yeah, that's my point. It might be simpler for translators to do a searh & replace, instead of walking through this commit.

**Comment by Girgias** [comment]
Ah right, yeah using skip-revcheck then makes more sense.

**Comment by mumumu** [comment]
Since example is the target in this case, I think it's better to match EN with other locales. I will follow this commit even if it is marked `[skip-revcheck]`.

**Comment by saundefined** [comment]
> Since example is the target in this case, I think it's better to match EN with other locales. I will follow this commit even if it is marked as `[skip-revcheck]`.

Agree

**Comment by cmb69** [comment]
Thanks all! So I've committed without `[skip-revcheck]`.

**Pull request merged**
