### PR TITLE
[skip-revcheck] Normalize &Constant; usage and create &Constructor;

### PR DESCRIPTION
**Pull request by alfsb**
While translating the ZMQ extension, I found some more files without entity usage on `<classsynopsisinfo>`, so I decided  to verify this on all manual.

This PR changes `Constants` to `&Constants;` in `<classsynopsisinfo>`, and also creates and changes the equivalent &Constructor;.

Before the patch:

```bash
$ grep -r "<classsynopsisinfo" | grep -v "<classsynopsisinfo>" | grep    "&" | wc
   1235    3702  136955
$ grep -r "<classsynopsisinfo" | grep -v "<classsynopsisinfo>" | grep -v "&" | wc
    148     492   16233
$ grep -rh "<classsynopsisinfo" | grep -v "<classsynopsisinfo>" | grep -v "&" | awk '{$1=$1};1' | sort | uniq -c
      2 <classsynopsisinfo role="comment">Access</classsynopsisinfo>
      1 <classsynopsisinfo role="comment">Anonymous Constructor</classsynopsisinfo>
      1 <classsynopsisinfo role="comment">Behaviour</classsynopsisinfo>
      1 <classsynopsisinfo role="comment">Cancellation</classsynopsisinfo>
      1 <classsynopsisinfo role="comment">Closing</classsynopsisinfo>
      1 <classsynopsisinfo role="comment">Constant for Infinitely Buffered</classsynopsisinfo>
     69 <classsynopsisinfo role="comment">Constants</classsynopsisinfo>
     48 <classsynopsisinfo role="comment">Constructor</classsynopsisinfo>
      2 <classsynopsisinfo role="comment">Constructors</classsynopsisinfo>
      1 <classsynopsisinfo role="comment">Create</classsynopsisinfo>
      1 <classsynopsisinfo role="comment">Event::$object (Channel) was closed</classsynopsisinfo>
      1 <classsynopsisinfo role="comment">Event::$object (Future) raised error</classsynopsisinfo>
      1 <classsynopsisinfo role="comment">Event::$object (Future) was cancelled</classsynopsisinfo>
      1 <classsynopsisinfo role="comment">Event::$object was read into Event::$value</classsynopsisinfo>
      1 <classsynopsisinfo role="comment">Execute</classsynopsisinfo>
      1 <classsynopsisinfo role="comment">Input</classsynopsisinfo>
      1 <classsynopsisinfo role="comment">Input for Event::$source written to Event::$object</classsynopsisinfo>
      1 <classsynopsisinfo role="comment">Join</classsynopsisinfo>
      2 <classsynopsisinfo role="comment">Methods</classsynopsisinfo>
      1 <classsynopsisinfo role="comment">Polling</classsynopsisinfo>
      1 <classsynopsisinfo role="comment">Resolution</classsynopsisinfo>
      1 <classsynopsisinfo role="comment">Runtime executing Event::$object (Future) was killed</classsynopsisinfo>
      1 <classsynopsisinfo role="comment">Shall be either Future or Channel</classsynopsisinfo>
      1 <classsynopsisinfo role="comment">Shall be one of <classname>Event\Type</classname> constants</classsynopsisinfo>
      1 <classsynopsisinfo role="comment">Shall be set for Read/Error events</classsynopsisinfo>
      1 <classsynopsisinfo role="comment">Shall be the source of the event (target name)</classsynopsisinfo>
      1 <classsynopsisinfo role="comment">Sharing</classsynopsisinfo>
      1 <classsynopsisinfo role="comment">State</classsynopsisinfo>
      1 <classsynopsisinfo role="comment">Synchronization</classsynopsisinfo>
      1 <classsynopsisinfo role="comment">Targets</classsynopsisinfo>
```

### CODE REVIEW

**Comment by salathe** [comment]
👍  on using `&Constants;`
👎  on introducing `&Constructor;`

**Comment by alfsb** [comment]
For the constructor, see por example this lines on ``:

```xml
    <classsynopsisinfo role="comment">&Properties;</classsynopsisinfo>
    <fieldsynopsis>
     <modifier>protected</modifier>
     <varname linkend="ui-window.props.controls">controls</varname>
    </fieldsynopsis>

    <classsynopsisinfo role="comment">Constructor</classsynopsisinfo>
    <xi:include xpointer="xmlns(db=http://docbook.org/ns/docbook) xpointer(id('class.ui-window')/db:refentry/db:refsect1[@role='description']/descendant::db:constructorsynopsis[not(@role='procedural')])" />
    
    <classsynopsisinfo role="comment">&Methods;</classsynopsisinfo>
    <xi:include xpointer="xmlns(db=http://docbook.org/ns/docbook) xpointer(id('class.ui-window')/db:refentry/db:refsect1[@role='description']/descendant::db:methodsynopsis[not(@role='procedural')])" />
    
    <classsynopsisinfo role="comment">&InheritedMethods;</classsynopsisinfo>
    <xi:include xpointer="xmlns(db=http://docbook.org/ns/docbook) xpointer(id('class.ui-control')/db:refentry/db:refsect1[@role='description']/descendant::db:methodsynopsis[not(@role='procedural')])" />
```

Observe that only "Constructor" need to be translated, and that `<classsynopsisinfo>` with *no* translated parts can be raw copied between all languages, facilitating a mechanical upgrade of the manual

**Comment by salathe** [comment]
If (and I think it's a big if) we want to split out constructors in the class synopses, then let's do it consistently for all relevant classes.   My preference would be to keep them under the methods, as currently for the vast majority of classes, but that's just _my_ preference.

**Comment by salathe** [comment]
If introducing `&Constructor;`, can we do something about the couple of classes that use a "Constructors" comment? I'd be fine with using `&Constructor;` there.

Also, the couple of `Methods` can become `&Methods;`.

**Comment by Girgias** [comment]
Also AFAIK most of the classes for the docs have the ``__constructor()`` be the first method, e.g. https://www.php.net/manual/en/class.arrayobject.php

**Comment by salathe** [comment]
By "split out constructors in the class synopses" I was referring to having a `<!-- Constructor -->` comment in the (rendered) class synopsis, separate from `<!-- Methods -->`.  Very few classes currently have such.

**Comment by alfsb** [comment]
I will remake this PR, to only change/normalize the `&Constants;` usage.

**Pull request closed without merging**
