### PR TITLE
Document missing curl constants added in 7.3.x

### PR DESCRIPTION
**Pull request by ekinhbayar**
FYI, I was looking at the following blame and curl's symbol versions reference for these changes:
[blame](https://github.com/php/php-src/blame/494615fcb8c1fb5984e0e7d666e51a2dfc6bee55/UPGRADING#L570)
[symbols in versions](https://github.com/curl/curl/blob/master/docs/libcurl/symbols-in-versions)

There are two commits of interest from the blame:
[Add constants from curl 7.50 to 7.55](https://github.com/php/php-src/commit/02b2dbb7242cba4324ceebe27fe8ad1e5eedc818) - merged into 7.3.0RC3
[Add constants from curl 7.56 to 7.61](https://github.com/php/php-src/commit/64881a1e64b47cb612d358f2ebf234defe314e90) - merged into 7.3.0RC3

### CODE REVIEW

**Comment by cmb69** [comment]
Thanks for the PR! The `CURLINFO_*` constants should also listed on the [`curl_getinfo` page](https://www.php.net/curl-getinfo), and the `CURLOPT_*` constants on the [`curl_setopt` page](https://www.php.net/curl-setopt).

**Comment by ekinhbayar** [comment]
> Thanks for the PR! The `CURLINFO_*` constants should also listed on the [`curl_getinfo` page](https://www.php.net/curl-getinfo), and the `CURLOPT_*` constants on the [`curl_setopt` page](https://www.php.net/curl-setopt).

Cool, will look at that page as well. @cmb69, should these two files be included in this PR or separately?

**Comment by cmb69** [comment]
If you like to do it, it would be nice to have all relevant changes for these constants bundled in one PR.

**Comment by ekinhbayar** [comment]
@cmb69, I think I've got them all listed in both pages as well now.

**Comment by ekinhbayar** [comment]
@PeeHaa thanks! I think I've covered all the requested changes now.

**Comment by nikic** [comment]
@php-pulls merge

**Comment by nikic** [comment]
Closing manually, as this has landed in SVN, but won't be picked up in the Git repo right away due to the pending mirroring switchover.

**Pull request closed without merging**
