### PR TITLE
Standardize casing for Enum examples.

### PR DESCRIPTION
**Pull request by Crell**
I just realized I had this branch lying around.  I thought I'd filed a PR for it months ago. :cry:

### CODE REVIEW

**Review by cmb69 — APPROVED** [review]
Thank you!

**Comment by TimWolla** [comment]
The whitespace check fails, because this is already applied. Duplicate of #1785.

**Comment by cmb69** [comment]
Ah, good catch!

**Comment by Crell** [comment]
D'Oh!  My branch never got deleted afterward; that's what confused me.  I knew this was familiar... 😄

**Pull request closed without merging**
