### PR TITLE
Update ext/ldap signatures to match PHP-8

### PR DESCRIPTION
**Pull request by MCMic**
Used gen_stub.php to update information in method synopses.
Had to fix ldap_connect by hand because of the deprecated signature
 information.

### CODE REVIEW

**Comment by MCMic** [comment]
What is the situation for this merge request and others tagged methodsynopses, is someone reviewing/merging them?

**Comment by cmb69** [comment]
Yes, we're [working on that](https://github.com/php/doc-en/pulls?q=label%3Amethodsynopses+is%3Aclosed); it's just a bit much for the doc team, currently.

**Comment by cmb69** [comment]
I have applied (and amendent) most of the changes, but left out `ldap_connect()`, `ldap_list()`, `ldap_read()` and `ldap_search()` because it is not quite clear to me which changes have been applied compared to PHP 7 (and these should be documented). This needs closer review. Could you please rebase to make that easier?

**Comment by MCMic** [comment]
> I have applied (and amendent) most of the changes, but left out `ldap_connect()`, `ldap_list()`, `ldap_read()` and `ldap_search()` because it is not quite clear to me which changes have been applied compared to PHP 7 (and these should be documented). This needs closer review. Could you please rebase to make that easier?

I rebased.

It’s really hard to answer what changed, because what the documentation said, what the code was doing and what the code was supposed to do were 3 different things. So I tried my best to fix that and to have sane default values for all attributes so that named parameters can be used in calls to ldap functions.

**Comment by cmb69** [comment]
Yeah, it's quite difficult. I made some amendments, the best I could.

**Comment by MCMic** [comment]
> Yeah, it's quite difficult. I made some amendments, the best I could.

Thank you.

The pages still list «(PHP 4, PHP 5, PHP 7)» in the version list (here for ldap_search).
How is this list handled, will it be automatically updated?

**Comment by cmb69** [comment]
There are versions.xml files, where PHP 8 support will have to be added. I think we can do that with a script.

**Pull request closed without merging**
