### PR TITLE
Documentation of index reset effect of some functions - issue #876

### PR DESCRIPTION
**Pull request by Salomon88**

### CODE REVIEW

**Comment by cmb69** [comment]
Thank you! I suggest to move the definition of the `note.reset-index` entity to just below the `note.sort-unstable` entity definition.

**Comment by Salomon88** [comment]
> Thank you! I suggest to move the definition of the `note.reset-index` entity to just below the `note.sort-unstable` entity definition.

Hello! Unfortunately, not all functions have link on `note.sort-unstable` , for example `array-unshift.xml`

**Comment by cmb69** [comment]
I didn't mean to merge both entitiy definition, but rather to move the new definition upwards, so that both are close to each other.

**Comment by Salomon88** [comment]
> I didn't mean to merge both entitiy definition, but rather to move the new definition upwards, so that both are close to each other.

Done

**Comment by cmb69** [comment]
Thank you!

**Pull request merged**
