### PR TITLE
Update simplexmlelement.xml

### PR DESCRIPTION
**Pull request by WinterSilence**
Updated by `ReflectionClass`

### CODE REVIEW

**Review by saundefined — COMMENTED** [review]
Thanks for PR!

PHP version for documentation is 7.0, `Countable` implemented later.
Before PHP 7.3 `is_countable(new SimpleXMLElement())` throws an exception.

Perhaps a changelog or note should also be added?
@cmb69 what do you think?

**Comment by cmb69** [comment]
Yes, there should be a changelog entry (I think it's Countable as of PHP 7.4.0, only). Also, as of PHP 8.0.0, the signature is actually `class SimpleXMLElement implements Stringable, Countable, RecursiveIterator`; that should be documented in the first place, and respective changelog entries should be added. It might be worthwhile to wait how the semi-automated classsynopsis updates (PR #839) will go.

**Comment by WinterSilence** [comment]
@saundefined 
> Before PHP 7.3 is_countable(new SimpleXMLElement()) throws an exception.

but `Countable` added only in 7.4... :rofl

**Comment by WinterSilence** [comment]
@cmb69 
> It might be worthwhile to wait how the semi-automated classsynopsis updates (PR #839) will go.

as after 7.4? 🤣

**Comment by cmb69** [comment]
To clarify: SimpleXMLElement supported `count()` forever; prior to PHP 7.4.0, this was done due to an internal mechanism; as of PHP 7.4.0, it properly implements `Countable`.

Regarding PR #839: I hope we can resolve this soon. If so, semi-automatic updates can be done for all classes, so that this PR would be obsolete.

**Pull request closed without merging**
