### PR TITLE
Capitalize the first letter of a sentence in match.xml

### PR DESCRIPTION
**Pull request by zors1**

### CODE REVIEW

**Comment by kamil-tekiela** [comment]
Thanks for the PR. Despite `match` being the first word, it is a PHP keyword and we don't usually capitalize PHP keywords. I understand that this sentence might not be clear enough, so if you want you can propose a different variant, but please don't capitalize keywords, function names, etc.

**Comment by zors1** [comment]
Ok, sorry about that. The word match is capitalized in the bulleted list describing the key differences between switch and match, so I thought it should be capitalized there too.

**Comment by cmb69** [comment]
Ah, right. It should *not* be capitalized in the bulleted list either.

**Comment by zors1** [comment]
Can I submit a pull request that will fix this?

**Comment by kamil-tekiela** [comment]
Good catch! Yes, please submit a PR to change the capitalization in the list.

**Pull request closed without merging**
