### PR TITLE
Add preg_last_error_msg documentation

### PR DESCRIPTION
**Pull request by nicoSWD**
This PR adds the documentation for `preg_last_error_msg`, added in [php-src/pull/5185](https://github.com/php/php-src/pull/5185)

Here's a rendered version of the manual page
Screenshot

### CODE REVIEW

**Comment by nikic** [comment]
@salathe @cmb69 What's our policy on docs for functions in not yet released PHP versions?

**Comment by cmb69** [comment]
Usually, we document only after features have been released (GA).

**Comment by nicoSWD** [comment]
@nikic @cmb69 fair enough. Should I close and re-submit this PR once it's released?

**Comment by nikic** [comment]
As we tend to do lag behind when it comes to updating the manual for new PHP versions, maybe it would make sense to include the documentation right away, but add a warning box along the lines of "This function is only available in pre-release versions of PHP" or so?

**Comment by cmb69** [comment]
Another option would be to keep such PRs open, but tag them with something like "PHP 8.0", so they can be merged when the migration guide is written.

**Comment by salathe** [comment]
> Another option would be to keep such PRs open, but tag them with something like "PHP 8.0", so they can be merged when the migration guide is written.

For what it's worth, this is my preference.

**Comment by cmb69** [comment]
I've did that now, but actually a PHP 8.0 milestone might be more apt.

**Comment by divinity76** [comment]
can't we just have a PHP8 branch where we put all the PHP8 stuff and merge on release?

**Comment by cmb69** [comment]
Thanks for the fine patch, @nicoSWD! I have applied it as http://svn.php.net/viewvc?view=revision&revision=350809.

**Pull request closed without merging**
