### PR TITLE
Add PECL in front of version numbers in changelogs

### PR DESCRIPTION
**Pull request by BenMorel**
As discussed in https://github.com/php/doc-en/pull/161#discussion_r511020631 with @cmb69, this PR adds the PECL package name in front of the PECL versions in the changelogs, to avoid confusing them with PHP versions.

The changes in this PR were generated using this script:
https://gist.github.com/BenMorel/19499bf5c918cd0ea0f0b3f27a5a8254

Open question: is `/reference/<name>/` always a PECL package name?

### CODE REVIEW

**Comment by cmb69** [comment]
> Open question: is /reference/<name>/ always a PECL package name?

No, it is not. It can be a bundled extension as well (e.g. ldap), but it also can be something made up (e.g. var, image). That is something that bugs me for the automatic signature generation, too.

**Comment by cmb69** [comment]
It might be possible to determine whether a package is a PECL package, by looking at the reference/*/version.xml files. Or, maybe better anyway, just have a manually compiled list.

**Comment by BenMorel** [comment]
Here is a list of the unique packages affected by this PR:

- apcu
- event
- expect
- geoip
- imagick
- memcached
- mongo
- mongodb
- oauth
- rar
- sdo
- solr
- sphinx
- stomp
- sync
- win32service
- xhprof
- yaml

From a quick search, it looks like all of them are PECL packages! :+1:

**Comment by cmb69** [comment]
Indeed! Thanks for checking, and the PR in general! Applied as http://svn.php.net/viewvc?view=revision&revision=350988.

**Comment by BenMorel** [comment]
Thanks! :+1:

**Pull request closed without merging**
