### PR TITLE
fpassthru error description (bug 81067)

### PR DESCRIPTION
**Pull request by saundefined**
Related bug [81067](https://bugs.php.net/bug.php?id=81067).

### CODE REVIEW

**Comment by cmb69** [comment]
Thanks for the PR! I'm not sure if we should document TypeErrors for individual functions, though. I mean passing invalid types is supposed to always throw a TypeError as of PHP 8.0.0. Resources are somewhat special, but still. @Girgias, what do you think?

**Comment by Girgias** [comment]
I'm not really keen on this, the docs do mention that this is invoking undefined behaviour (see https://www.php.net/manual/en/functions.internal.php). I think just the return section changes are sufficient.

**Comment by saundefined** [comment]
Thank you! Fixed

**Review by cmb69 — APPROVED** [review]
Thanks!

**Pull request merged**
