### PR TITLE
setup.xml: replace the broken URL

### PR DESCRIPTION
**Pull request by mmalferov**
The Microsoft Knowledge Base does not contain the "Best Practices and Recommendations for authors of Discretionary Access Control Service Lists" page. And I couldn't find a copy of the material on the MKB website. I have replaced the link to the most reputable, in my humble opinion, site, which still keeps a copy of the original article

### CODE REVIEW

**Comment by cmb69** [comment]
Hmm, that article is apparently very old anyway. Maybe @macintoshplus has an idea where to link to instead?

**Comment by macintoshplus** [comment]
I haven't found the new documentation page. This link is a mirror of old Microsoft documentation.

This process of managing service rights is not efficient. I prepare a new version of Win32Service with a new method to replace this tool.

**Comment by macintoshplus** [comment]
The version 1.1.0 with the replacement method is in beta release. 

I prefer to keep a valid link for old usage and add the new rights management process available for version 1.1+

You can merge this PR and I write another one to add the rights management process.

**Review by macintoshplus — APPROVED** [review]

**Comment by macintoshplus** [comment]
> Especially if the URL is going to change again, I suggest to add an entity declaration to https://github.com/php/doc-base/blob/master/entities/global.ent, so that translations don't have to update in the future.

Good idea.

I have open this PR to add the URL in entities: https://github.com/php/doc-base/pull/164

I have integrated then entity usage in my PR #3871

**Comment by jimwins** [comment]
@macintoshplus Can this be closed now that those other PRs have landed?

**Comment by cmb69** [comment]
Indeed, this PR is superseded by #3871.

**Comment by macintoshplus** [comment]
> @macintoshplus Can this be closed now that those other PRs have landed?

Yes. Thank you for your PR.

**Pull request closed without merging**
