### PR TITLE
Use new class synopsis markup

### PR DESCRIPTION
**Pull request by kocsismate**
Following https://github.com/php/phd/pull/77

### CODE REVIEW

**Review by TimWolla — COMMENTED** [review]
ack for reference/random/

**Review by Girgias — CHANGES_REQUESTED** [review]
Can we not just fix the interfaces for the time being, and possibly continue to use the legacy markup for classes?

Not sure if I really want to dump a 260 file change onto translations, but maybe @mumumu, @saundefined, @sy-records are fine with that?

**Comment by saundefined** [comment]
It's not a big problem for me, thanks!

But I'd also listen to other translators' opinions as well.

**Comment by kocsismate** [comment]
> an we not just fix the interfaces for the time being, and possibly continue to use the legacy markup for classes?

I'm fine with fixing the interfaces first in a separate commit, but I'd be a bit upset if classes had to use the old syntax because then I would have to conditionally generate a different markup for classes and interfaces which would complicate gen_stub even more.

**Comment by Girgias** [comment]
> > an we not just fix the interfaces for the time being, and possibly continue to use the legacy markup for classes?
> 
> I'm fine with fixing the interfaces first in a separate commit, but I'd be a bit upset if classes had to use the old syntax because then I would have to conditionally generate a different markup for classes and interfaces which would complicate gen_stub even more.

Yeah I would want them to be the same too, but let's first do interfaces to fix the immediate issues, and lets merge classes a tad later

**Comment by kocsismate** [comment]
OK, I'll create a new PR soon only containing the interfaces :)

**Comment by kocsismate** [comment]
@Girgias Can I merge this?

**Comment by Girgias** [comment]
Give me/doc-fr until the end of the week to try to get our stuff in order :)

**Comment by kocsismate** [comment]
@Girgias What about now? :)

**Pull request merged**
