### PR TITLE
new-features.xml Change `ucfirst` to `mb_ucfirst`

### PR DESCRIPTION
**Pull request by mmalferov**
Can we replace `ucfirst` with `mb_ucfirst` for the local first name when translation?

### CODE REVIEW

**Review by TimWolla — COMMENTED** [review]
Perhaps this example should be entirely replaced by the one in https://github.com/php/web-php/pull/1079#pullrequestreview-2389016000, because of the reasons given there?

**Comment by Girgias** [comment]
Yeah, using the new example might be a good idea.

**Comment by kamil-tekiela** [comment]
Let's use the other example. If you'd like, please create a new PR that copies the example over to this page. 

As an aside, using `mb_ucfirst` on a byte string from `strtolower` is incorrect.

**Comment by mmalferov** [comment]
> As an aside, using `mb_ucfirst` on a byte string from `strtolower` is incorrect.

Could you explain why and give an example, please

**Comment by kamil-tekiela** [comment]
> > As an aside, using `mb_ucfirst` on a byte string from `strtolower` is incorrect.
> 
> Could you explain why and give an example, please

Well, it simply doesn't make much sense. If the string is multibyte then use `mb_strtolower`, else use `ucfirst`

**Comment by mmalferov** [comment]
In the Russian documentation, it was agreed to translate the text in the code examples into the native language that is to be translated (if the translation does not break the code example). Therefore, we wanted to translate the name `Peter` as  `«Пётр»`

```php
<?php

$firstName = 'peter';
$cyrillicName = 'пётр';

// Converts all ASCII chars to lowercase, then capitalized the first ASCII char
echo ucfirst(strtolower($firstName)), "\n"; //  Prints 'Peter'

// The same, but the first character 'п' (cyrillic 'pe') is 2 bytes length, therefore  ucfirst() will ignore it
echo ucfirst(strtolower($cyrillicName)), "\n"; // Prints 'пётр' (note, the first char is in lowercase) - it is bad


// Whereas mb_ucfirst() capitalizes the first 2-byte alphabetic character 'п' (pe)
echo mb_ucfirst(strtolower($cyrillicName)), "\n"; // Prints 'Пётр' - well good!
```

The mb_ucfirst() did not break the example with the English name, and it made sense to convert the first letter of the Cyrillic name even when working with the strtolower(). For the rest, I agree—either we work with multibyte characters, or with ASCII ;)

**Pull request closed without merging**
