### PR TITLE
Fix return type explanation for array_recursive

### PR DESCRIPTION
**Pull request by othercorey**

### CODE REVIEW

**Comment by cmb69** [comment]
I don't think this should be documented here. It is [generally undefined behavior to pass values of unexpected types to an internal function](https://www.php.net/manual/en/functions.internal.php).

**Comment by othercorey** [comment]
So just drop the null entirely?

**Comment by cmb69** [comment]
Oh, right!

**Comment by othercorey** [comment]
Should I say previously returned null on error without explaining? I guess it was just a mess when this stuff happened before throwing errors.

I'm simply updating missing docs after updating psalms function signatures.

**Comment by cmb69** [comment]
No, I wouldn't even mention the `NULL` on failure.

**Review by cmb69 — APPROVED** [review]
Thank you!

**Pull request merged**
