### PR TITLE
Additional revisions to ucwords

### PR DESCRIPTION
**Pull request by tiffany-taylor**
My apologies for my trigger happy merging in https://github.com/php/doc-en/pull/726.

This PR includes revisions as specified by @salathe.

### CODE REVIEW

**Comment by cmb69** [comment]
According to this description, `ucwords("1hello")` would return `"1Hello"`, but https://3v4l.org/9b9Op. :)

**Comment by tiffany-taylor** [comment]
> For this function, a word is defined as a string of characters, begins with an alphabetical character, and is delimited by a character from the `separators` parameter.

This slightly changes the suggestion salathe gave, but I think it's an improvement? Maybe?

**Comment by salathe** [comment]
> This PR includes revisions as specified by @salathe.
> ```
> For this function, a word is defined as a string of alphabetic characters
> that are not listed in the separators parameter.
> ```

What is written is not what I suggested (at least, tried to suggest) at all.  Again, the definition of a word, for `ucwords()`, is a string of characters that aren't in the separators list. Nothing more or less.

For example:
```
Input:  this is bob, and he :is a.fine fellow.
Words:  1111 22 3333 444 55 666 777777 8888888
Output: This Is Bob, And He :is A.fine Fellow.
```

> > For this function, a word is defined as a string of characters, begins with an alphabetical character, and is delimited by a character from the `separators` parameter.
>
> This slightly changes the suggestion salathe gave, but I think it's an improvement? Maybe?

This is not an improvement, nor is it a *slight* change.  A word doesn't need to:
* Begin with an alphabetical character. With the default separators list, `-----` is a word.
* Be delimited by a character from the `separators` parameter. E.g. for single-word input.

My suggestion, as before, is to keep things concise, precise, and correct.  A word, for `ucwords()`, is a string of characters that aren't in the separators list.

**Comment by tiffany-taylor** [comment]
I understand now. I had to spend a little time playing around with the function. Thank you for the explanation.

**Review by cmb69 — APPROVED** [review]
Thank you!

**Review by salathe — APPROVED** [review]

**Review by sy-records — APPROVED** [review]

**Pull request merged**
