### PR TITLE
PHP 8.3: legacy assertion have been deprecated

### PR DESCRIPTION
**Pull request by Girgias**
Yanked the table markup for the constants just for assert and shoved it in a ``<section>`` tag.

This requires it moving it to the end to comply with the DTD.

### CODE REVIEW

**Comment by TimWolla** [comment]
> Yanked the table markup for the constants just for assert and shoved it in a `<section>` tag.

Why? Can't you slap `&warn.deprecated.feature-8-3-0;` onto the beginnning of the section?

**Comment by Girgias** [comment]
> > Yanked the table markup for the constants just for assert and shoved it in a `<section>` tag.
> 
> Why? Can't you slap `&warn.deprecated.feature-8-3-0;` onto the beginnning of the section?

I suppose that's an option I just worry people might not understand this is for all assert constants

**Comment by TimWolla** [comment]
> I suppose that's an option I just worry people might not understand this is for all assert constants

Including the warning into the “Descrption” column doesn't look too bad to me:

image

Source code is:

```
   <tbody>
    <row xml:id="constant.assert-active">
     <entry><constant>ASSERT_ACTIVE</constant></entry>
     <entry><link linkend="ini.assert.active">assert.active</link></entry>
     <entry>
      Enable <function>assert</function> evaluation.
      &warn.deprecated.feature-8-3-0;
     </entry>
    </row>
    <row xml:id="constant.assert-callback">
     <entry><constant>ASSERT_CALLBACK</constant></entry>
     <entry><link linkend="ini.assert.callback">assert.callback</link></entry>
     <entry>
      Callback to call on failed assertions.
      &warn.deprecated.feature-8-3-0;
     </entry>
    </row>
    <row xml:id="constant.assert-bail">
     <entry><constant>ASSERT_BAIL</constant></entry>
     <entry><link linkend="ini.assert.bail">assert.bail</link></entry>
     <entry>
      Terminate execution on failed assertions.
      &warn.deprecated.feature-8-3-0;
     </entry>
    </row>
    <row xml:id="constant.assert-exception">
     <entry><constant>ASSERT_EXCEPTION</constant></entry>
     <entry><link linkend="ini.assert.exception">assert.exception</link></entry>
     <entry>
      Issues a PHP warning for each failed assertion
      &warn.deprecated.feature-8-3-0;
     </entry>
    </row>
    <row xml:id="constant.assert-warning">
     <entry><constant>ASSERT_WARNING</constant></entry>
     <entry><link linkend="ini.assert.warning">assert.warning</link></entry>
     <entry>
      Issues a PHP warning for each failed assertion
      &warn.deprecated.feature-8-3-0;
     </entry>
    </row>
    <row xml:id="constant.assert-quiet-eval">
     <entry><constant>ASSERT_QUIET_EVAL</constant></entry>
     <entry><link linkend="ini.assert.quiet-eval">assert.quiet_eval</link></entry>
     <entry>
      Disable <literal>error_reporting</literal> during assertion expression evaluation.
      &warn.feature.removed-8-0-0;
     </entry>
    </row>
   </tbody>
```

**Review by TimWolla — APPROVED** [review]
LGTM. I'll likely send a follow-up to clean the page for `assert()` from all the legacy cruft.

**Pull request merged**
