### PR TITLE
Extend ext/random documentation (2)

### PR DESCRIPTION
**Pull request by TimWolla**

### CODE REVIEW

**Review by cmb69 — COMMENTED** [review]
Thank you! This is fine, except that the (3?) new URLs should be defined as XML entities in https://github.com/php/doc-base/blob/master/entities/global.ent (so that when they change, translations won't have to be updated).

**Comment by TimWolla** [comment]
@zeriyoshi Friendly ping, have you seen the review request? :smiley:

**Review by Girgias — APPROVED** [review]
Can't comment on the accuracy of the ``seed`` parameter description, but LGTM

**Review by zeriyoshi — APPROVED** [review]

**Comment by zeriyoshi** [comment]
@TimWolla 
I did not have a very deep understanding of the documentation system and was waiting for the noted items to be resolved.
I think we're good to go, thanks!

**Pull request merged**
