### PR TITLE
Changed the incorrect false for null.

### LINKED ISSUE #804: documentation: dom_import_simplexml incorrect return value.
From manual page: https://php.net/function.dom-import-simplexml

--- Return value is mentioned to be `The DOMElement node added or false if any errors occur.`
While the actual return type is `DOMElement|null`

### PR DESCRIPTION
**Pull request by KevinVanSonsbeek**
Fixes #804

### CODE REVIEW

**Comment by KevinVanSonsbeek** [comment]
Closed the PR due to the issue possibly being incorrect.

**Comment by cmb69** [comment]
Well, the fix is correct (the unrelated whitespace changes should be avoided, though).

**Comment by KevinVanSonsbeek** [comment]
> Well, the fix is correct (the unrelated whitespace changes should be avoided, though).

Yeah. It's just that when i was looking at the source code. I noticed the behaviour of the method changed when going to php8. The stub added tells the return type is nullable. But the null returns have been replaced with throw returns.

**Comment by cmb69** [comment]
The stub has just been fixed. Please change the method signature and the return value section; I don't think that we need a changelog entry.

**Comment by KevinVanSonsbeek** [comment]
> The stub has just been fixed. Please change the method signature and the return value section; I don't think that we need a changelog entry.

Might not be needed. But it could be handy to add.

**Review by cmb69 — APPROVED** [review]
Thank you!

**Pull request merged**
