### PR TITLE
Fix typo in Swoole\Process::kill

### PR DESCRIPTION
**Pull request by sy-records**

### CODE REVIEW

**Comment by cmb69** [comment]
Thank you!

**Comment by sy-records** [comment]
@cmb69 Hi, can I request an account with @php.net?

**Comment by cmb69** [comment]
Frankly, I'm not sure about php.net accounts; these may no longer make sense, but instead you likely need push access to this repo instead. @nikic, can you please clarify?

**Comment by sy-records** [comment]
Yeah, PHP is now migrated to GitHub 😂

**Comment by nikic** [comment]
@cmb69 As bugs and wiki are still connected to php.net accounts, I think it makes sense to still request one. When approving the account, @sy-records should also be added to the doc team here.

**Comment by sy-records** [comment]
@nikic Where can I submit my request? Is it here? https://www.php.net/git-php.php

**Comment by nikic** [comment]
@sy-records Yes, that's right.

**Comment by sy-records** [comment]
image
I got this...

**Comment by nikic** [comment]
@sy-records Heh, you need to uncheck all checkboxes on the page ^^

**Comment by sy-records** [comment]
cool. Thanks, I submitted the request 👍🏻

**Comment by cmb69** [comment]
Your php.net account has been approved, and I've sent an invitation for the doc team.

**Comment by sy-records** [comment]
thanks!

**Pull request merged**
