### PR TITLE
fix #80766  namespaced assert is no longer allowed

### PR DESCRIPTION
**Pull request by jhdxr**

### CODE REVIEW

**Review by cmb69 — APPROVED** [review]
Ah, thanks, very nice! This resolves the unadressed issue in PR #473.

**Comment by jhdxr** [comment]
Hi @cmb69, I don't have write access to this repo. so please feel free to merge it if you think it's good to go. Alternatively, I'm glad to have the write access here to help to improve the doc.

**Review by sy-records — APPROVED** [review]

**Review by cmb69 — APPROVED** [review]
I've added you to the doc-team.

**Comment by jhdxr** [comment]
ok. thanks.

**Pull request merged**
