### PR TITLE
Remove PHP 5 specific documentation

### PR DESCRIPTION
**Pull request by cmb69**
This is @Sobak's previous work; I just rebased onto current master and fixed conflicts. Since these are quite comprehensive changes, review is very welcome.

### CODE REVIEW

**Comment by salathe** [comment]
Nice. 🥇 

Be sure to grab the "PHP 5" archives and stow them somewhere safe before applying this.

**Comment by cmb69** [comment]
@salathe, see https://github.com/php/web-php/pull/341. Could you put the PHP 5 archives to http://doc.php.net/archives/?

**Comment by salathe** [comment]
@cmb the PHP 5 archives are now in Git (https://github.com/php/web-doc/commit/aa24ddb51f9ed3824ef1d2643d9f5072356a2a62) and available at http://doc.php.net/archives/php5/

**Comment by cmb69** [comment]
WIP:

* commit 2-4 applied as [r350643](http://svn.php.net/viewvc?view=revision&revision=350643) and [r350644](http://svn.php.net/viewvc?view=revision&revision=350644)

**Comment by Sobak** [comment]
@cmb69 Hi Christoph :) I'm very thankful that you pushed the work forward. Sadly, I'm totally swamped due to my job and it's unlikely to change very soon so as much as I'd like to help, I fail to motivate in my free time.

I just want to point out that this is not a complete removal. There are still changelogs for newer PHP 5.x versions left and probably a ton of inline mentions. However, now that the effort begun on the live repo, I'll at least try to contribute some tiny bits from time to time.

Kudos for all the work you do!

**Pull request closed without merging**
