### PR TITLE
Add missing period on webPhar page

### PR DESCRIPTION
**Pull request by zors1**
In addition to #766

### CODE REVIEW

**Review by tiffany-taylor — APPROVED** [review]
Thanks!

**Comment by salathe** [comment]
👎  The convention is to **not** have a period at the end of `refpurpose`s.

**Comment by cmb69** [comment]
I think the punctuation (and maybe more) is generally wrong; at least for me this refpurpose yields `E_PARSE_ERROR`.

**Comment by tiffany-taylor** [comment]
I think `<refpurpose>` should probably be changed to `<para>` if the punctuation breaks the build.

**Comment by cmb69** [comment]
There's no problem with the build (doc is valid), but I think the purpose of this function should be described more understandably (and there definitly shouldn't be a period at all).

**Pull request merged**
