### PR TITLE
MySQLi updating the documentation: There is no mysqli_warning_next

### PR DESCRIPTION
**Pull request by kamil-tekiela**
Removed invalid line from versions.xml

### CODE REVIEW

**Comment by cmb69** [comment]
Well, actually [there is](https://www.php.net/manual/en/mysqli-warning.next.php). :)

**Comment by cmb69** [comment]
Oops!

**Comment by cmb69** [comment]
Thanks! Applied as http://svn.php.net/viewvc?view=revision&revision=351029.

**Comment by kamil-tekiela** [comment]
> Well, actually [there is](https://www.php.net/manual/en/mysqli-warning.next.php). :)

That's `mysqli_warning::next` which is a method of the class and I mentioned a function. But I assume you realized that already :)

**Pull request closed without merging**
