### PR TITLE
Remove spldoublylinkedlist construct

### PR DESCRIPTION
**Pull request by sy-records**
close https://github.com/php/doc-en/issues/640

### CODE REVIEW

**Comment by cmb69** [comment]
Thak you! But see https://github.com/php/doc-en/pull/641/checks?check_run_id=2706906842#step:5:30. The inclusion of the constructorsynopsis on the class page should be commented out.

**Comment by nikic** [comment]
@cmb69 Hrm, why does that not cause a build failure?

**Comment by cmb69** [comment]
Oh, on a closer look I am surprised by that. Usually, there should be an [`<xi:fallback>`](https://github.com/php/doc-base/blob/f4eff8d4b5b2afb8220027194a2ba4811903f51a/RFC/skeletons/classname.xml#L65-L67), in which case the error would be bogus (apparently, a glitch in libxml2 or the configure script), but in this case there isn't:
https://github.com/php/doc-en/blob/3263a6218e51bab67de19e1cc4c772aca35a523f/reference/spl/spldoublylinkedlist.xml#L87

**Comment by sy-records** [comment]
> @cmb69 Hrm, why does that not cause a build failure?

Stops only when a fatal error is encountered

https://github.com/php/doc-base/blob/master/configure.php#L223-L227

**Comment by cmb69** [comment]
Ah, thanks!

**Review by cmb69 — APPROVED** [review]

**Pull request merged**
