### PR TITLE
Mark up unspecific constants as replaceable

### PR DESCRIPTION
**Pull request by cmb69**
Great idea of @Girgias, in my opinion.

### CODE REVIEW

**Comment by Girgias** [comment]
Does our DTD really not allow ``<constant>LC_<replaceable>*</replaceable></constant>``?

Otherwise, LGTM, but I would wait a bit before merging to not put too much strain on translation before the release of 8.2.

**Comment by Girgias** [comment]
> Does our DTD really not allow `<constant>LC_<replaceable>*</replaceable></constant>`?
> 
> Otherwise, LGTM, but I would wait a bit before merging to not put too much strain on translation before the release of 8.2.

Now that I think about it, having the replaceable tag be just after the constant one will probably help if (one can dream) we get links to constants automatically generated as those will need to be ignored

**Comment by cmb69** [comment]
> Does our DTD really not allow `<constant>LC_<replaceable>*</replaceable></constant>`?

Yeah, I got a failure when running `configure`, although the [constant spec](https://tdg.docbook.org/tdg/4.5/constant.html) says:

> Mixed Content Model
constant ::=
(#PCDATA|[replaceable](https://tdg.docbook.org/tdg/4.5/replaceable.html)|[inlinegraphic](https://tdg.docbook.org/tdg/4.5/inlinegraphic.html)|[inlinemediaobject](https://tdg.docbook.org/tdg/4.5/inlinemediaobject.html)|[indexterm](https://tdg.docbook.org/tdg/4.5/indexterm.html)|
 [beginpage](https://tdg.docbook.org/tdg/4.5/beginpage.html))*

> Now that I think about it, having the replaceable tag be just after the constant one will probably help if (one can dream) we get links to constants automatically generated as those will need to be ignored

Indeed, avoinding mixed content in `<constant>`s should make that easier.

**Comment by cmb69** [comment]
> What was the failure? A quick search/replace to the `<constant>FOO_<replaceable>*</replaceable></constant>` format didn't result in a failure for me locally.

I've tried again, and indeed it works. I must have messed something up in my first attempt.

> I don't buy the argument that `<constant><replaceable>FOO_*</replaceable></constant>` should be (any meaningful amount) easier to work with than `<constant>FOO_<replaceable>*</replaceable></constant>` (e.g. for adding links, generating lists of constants, etc.).

Well, there isn't probably much of a difference, so I'm pushing a commit where only the `*`s are `<replaceable>`.

**Comment by cmb69** [comment]
This has at least partially been done already, so I'm closing this PR.

**Pull request closed without merging**
