### PR TITLE
Improve the document of openssl-pkcs7-read

### PR DESCRIPTION
**Pull request by vjardin**
The input shall be a string data.

### CODE REVIEW

**Comment by vjardin** [comment]
Please, what's next in order to get it reviewed/approved ?

**Comment by Girgias** [comment]
Can you squash/rebase this into one commit?

**Comment by vjardin** [comment]
thanks @Girgias, enclosed the squash'd update.

**Comment by vjardin** [comment]
Thanks. For my information when will it show up on https://www.php.net/manual/en/function.openssl-pkcs7-read.php ?

**Comment by Girgias** [comment]
Tomorrow after the docs are rebuilt (around 2AM IIRC)

**Comment by Girgias** [comment]
Actually I need to revert the param name change as it needs to match the stubs (for named arguments), if that should be changed can you make a PR against php-src?

**Comment by vjardin** [comment]
Understood. I'll try fixup the php mainstream stub too.

**Comment by vjardin** [comment]
Please, can you re-open this pull request ? It seems that I cannot.

**Comment by Girgias** [comment]
I cannot either, but until the stubs are updated upstream the docs should remain with this parameter name.

**Pull request merged**
