### PR TITLE
Fix bug 67034: Unable to compare DateInterval instances with == operator

### PR DESCRIPTION
**Pull request by cmb69**

### CODE REVIEW

**Comment by cmb69** [comment]
@derickr, I think just adding a respective paragraph to the `DateInterval` page should be sufficient.

@Girgias, please have a look at the "Uncomparable Values" section; is that okay, or should we explicitly specify the results?

**Comment by Girgias** [comment]
> @derickr, I think just adding a respective paragraph to the `DateInterval` page should be sufficient.
> 
> @Girgias, please have a look at the "Uncomparable Values" section; is that okay, or should we explicitly specify the results?

I think the current wording (modulo it being "incomparable" and not "uncomparable" (welcome to the English language)) is best, as we might want to actually change the behaviour when trying to compared incomparable values.

But maybe the comparison operator page already describes the behaviour?

**Comment by cmb69** [comment]
> But maybe the comparison operator page already describes the behaviour?

It only mentions "uncomparable"[sic] twice, but doesn't specify what that means. I'm going to update to use "incomparable".

**Review by Girgias — APPROVED** [review]
LGTM

**Pull request merged**
