### PR TITLE
Fix #896: InternalIterator is not documented

### LINKED ISSUE #896: InternalIterator class is reserved as of PHP 8.0.0
We cannot instantiate or extend global scope class `InternalIterator` which is introduced as of PHP 8.0.0 ( https://github.com/php/php-src/commit/ff19ec2df3ef0dca8c29be83eddcde58234f4095 ) and seems to be reserved as internal iterator classname, but this fact is Undocumented.

https://3v4l.org/OKO6a

We should document it in [appendices/migration80/incompatible.xml](https://github.com/php/doc-en/blob/master/appendices/migration80/incompatible.xml)?

### PR DESCRIPTION
**Pull request by cmb69**
This is a skeleton for now. Help to actually document the class is welcome!

### CODE REVIEW

**Comment by thinkverse** [comment]
For anyone wanting a bit of information about `InternalIterator`, it was introduced in PR (https://github.com/php/php-src/pull/5216).

From my limited understanding, it's the generic iterator class some PHP classes use internally to represent Traversable objects? For instance, running a WeakMaps `getIterator` method against an `instanceof \InternalIterator` returns true, as shown here ([3v4l.org/HRpmk](https://3v4l.org/HRpmk#v8.0.0)). Though I might be off so please, feel free to correct me if I am.

**Comment by cmb69** [comment]
@thinkverse, I think you're pretty much right on.

**Comment by Girgias** [comment]
Should we just merge this as is, and enhance later?

**Comment by cmb69** [comment]
I've fleshed that out a bit.

**Pull request closed without merging**
