### PR TITLE
Add missing cURL constants

### PR DESCRIPTION
**Pull request by haszi**
This PR adds the last few missing constants from https://github.com/php/doc-en/issues/2747. All constant descriptions and cURL version availability is based on the [cURL Symbols page](https://curl.se/libcurl/c/symbols-in-versions.html).

As the last commit sorts the constants which throws off the diff, this PR is definitely best reviewed commit by commit.

As a side note, I used [this script](https://gist.github.com/haszi/bca07054a7d4504d773d8d7fdfcffe2f) to sort the constants which may or may not be useful for doing the same in the translations.

### CODE REVIEW

**Comment by haszi** [comment]
@Girgias Could you take a look at this PR as well?

**Review by cmb69 — APPROVED** [review]
Thank you very much! In my opinion this is good to be merged (should probably not be squashed-merged). While I see some potential for futher improvements (a few descriptions are missing, lots of unmarked acronyms, and other minor details), let's not delay adding useful information to manual. We can still improve later.

**Comment by haszi** [comment]
> ...While I see some potential for futher improvements (a few descriptions are missing, lots of unmarked acronyms, and other minor details)...

I'm planning on doing this in a separate PR as there are a whole lot of constants in this file that need their descriptions entered and/or updated.

**Comment by Girgias** [comment]
I had forgotten about this sorry

**Pull request merged**
