### PR TITLE
[PHP 8.1] New in initializers

### PR DESCRIPTION
**Pull request by saundefined**
Related [RFC](https://wiki.php.net/rfc/new_in_initializers).

### CODE REVIEW

**Comment by mumumu** [comment]
Also, we should add the following description.

> Objects can also be passed to define() now. 

https://www.php.net/manual/en/migration81.new-features.php#migration81.new-features.core.new-in-initializer

**Comment by mumumu** [comment]
From, [RFC](https://wiki.php.net/rfc/new_in_initializers), we should add some more example code.

> New expressions are allowed in parameter default values, attribute arguments, static variable initializers and global class constant initializers. Parameter default values also include defaults for promoted properties: 

```php
static $x = new Foo;
 
const C = new Foo;
 
function test($param = new Foo) {}
 
#[AnAttribute(new Foo)]
class Test {
    public function __construct(
        public $prop = new Foo,
    ) {}
}
```

**Comment by mumumu** [comment]
Also, we should add the following `limitations`, maybe in `<note><para>...</para></note>` tag.

> The use of a dynamic or non-string class name or an anonymous class is not allowed. The use of argument unpacking is not allowed. The use of unsupported expressions as arguments is not allowed.

```php
// All not allowed (compile-time error):
function test(
    $a = new (CLASS_NAME_CONSTANT)(), // dynamic class name
    $b = new class {}, // anonymous class
    $c = new A(...[]), // argument unpacking
    $d = new B($abc), // unsupported constant expression
) {}
```

**Comment by saundefined** [comment]
@mumumu thanks for the review!

**Comment by Crell** [comment]
Thanks!

**Pull request merged**
