### PR TITLE
Add runkit7 documentation

### PR DESCRIPTION
**Pull request by TysonAndre**
Background: https://pecl.php.net/runkit was last updated in 2015.
I created the fork https://pecl.php.net/package/runkit7 to support php7.
See `https://github.com/php/web-rmtools/pull/10#issuecomment-496132527`
for background information.

I'm new to the workflow of setting up documentation for a new extension.

- Are there any issues preventing creating documentation for a fork with a
  similar API but different names?

  **If not, I'll proceed with filling in the missing sections and fixing
  param/return/constant info.**
- Are there any technical issues with generating documentation for overlapping ini
  settings? If there are, I'll take that out and replace it with a link.
- Various other parts of en/ reference runkit and need to be updated to
  also link to runkit7.
  (e.g. manual.xml.in, appendices, etc)

  I'm unfamiliar with which of those files are automatically generated,
  and how to locally ensure the doc build on php.net will pass.
  (I see unrelated errors running `phd -d doc-base/manual.xml` locally)
  (for now, added runkit7 to doc-base/manual.xml.in, ran php
  doc-base/configure.php, and
  `phd --docbook doc-base/.manual.xml --format xhtml`)

```patch
» svn diff
Index: manual.xml.in
===================================================================
--- manual.xml.in       (revision 349164)
+++ manual.xml.in       (working copy)
@@ -153,6 +153,7 @@
    &reference.info.book;
    &reference.phpdbg.book;
    &reference.runkit.book;
+   &reference.runkit7.book;
    &reference.scream.book;
    &reference.uopz.book;
    &reference.weakref.book;
```

### CODE REVIEW

**Comment by cmb69** [comment]
I see no general issues here, but the ini IDs are supposed to clash (what should be reported by doc-base\configure).

**Comment by TysonAndre** [comment]
> I see no general issues here, but the ini IDs are supposed to clash (what should be reported by doc-base\configure).

I'm not sure what the consequences of that are or if that's a blocker.
For now, I'm linking to runkit's ini settings, because there aren't any new settings yet.

I had to run `php doc-base/configure.php` every time before `phd` to get the new docs to render. The local chunked xml seems fine and the `phd` script runs without reporting errors related to runkit7.

**Comment by cmb69** [comment]
> For now, I'm linking to runkit's ini settings, because there aren't any new settings yet.

Ah, I missed that!

Then this is good to be merged. Only minor issue is reference/runkit7/book.developer.xml; I don't think this is ever needed (not even sure why that's generated in the first place, and what's its supposed purpose). IMO, just delete this file.

**Comment by TysonAndre** [comment]
This and the change to manual.xml.in were pushed to SVN. If there were any issues, please let me know.

**Comment by cmb69** [comment]
The SVN properties have not been set (see http://doc.php.net/tutorial/faq.php at the bottom of the page); done with http://svn.php.net/viewvc?view=revision&revision=349200.

**Pull request closed without merging**
