### PR TITLE
Document SensitiveParameter attributes - part 2

### PR DESCRIPTION
**Pull request by kocsismate**

### CODE REVIEW

**Comment by kocsismate** [comment]
cc @haszi

**Comment by haszi** [comment]
Looking at the attributes in the stub files, I've noticed that some functions/methods are missing both from `doc-en` and a consequence of that, from these PRs. The functions/methods are the following:
`sodium_crypto_aead_aegis128l_decrypt()`
`sodium_crypto_aead_aegis128l_encrypt()`
`sodium_crypto_aead_aegis256_decrypt()`
`sodium_crypto_aead_aegis256_encrypt()`
`PDO::connect()`
`pg_change_password()`

The following two functions are listed in `doc-en` but were not part of the two SensitiveParameter PRs:
`odbc_connect()`
`odbc_pconnect()`

Can `gen_stub` generate a list of function/methods that are not listed in the documentation? A list like the one you made for constants would be handy, I think.

**Comment by kocsismate** [comment]
> The following two functions are listed in doc-en but were not part of the two SensitiveParameter PRs:
odbc_connect()
odbc_pconnect()

Yes, I explicitly left these out because I recently migrated these resources to objects, so a few months later we have to change the documentation anyway, and I didn't want to bother with manual changes for now.


> Can gen_stub generate a list of function/methods that are not listed in the documentation? A list like the one you made for constants would be handy, I think.

Yes, it can, just like I did for constants. I created https://github.com/php/doc-en/issues/2163
 and https://github.com/php/doc-en/issues/2162 ~1.5 years ago, and I last updated them a few months ago. You can also run `phpstub --verify-manual ./ ../doc-en/ ` manually to have a completely up-to-date output. I share one here:
https://gist.github.com/kocsismate/49f229910df3b1033d4ae8afdda52692

**Comment by haszi** [comment]
> ./build/gen_stub.php --verify-manual ./ ../doc-en/

Thanks! That's exactly what I was looking for. :-)

**Review by Girgias — APPROVED** [review]

**Pull request merged**
