### PR TITLE
Namespaces/importing: update the list of structures which can be imported

### PR DESCRIPTION
**Pull request by jrfnl**
... for completeness.

Page link: https://www.php.net/manual/en/language.namespaces.importing.php

### CODE REVIEW

**Comment by cmb69** [comment]
Ah, thank you! That raises the point about a [general naming for these "entities"](https://github.com/php/doc-en/pull/1732#issuecomment-1203771553). Would you have a suggestion?

**Comment by jrfnl** [comment]
> Ah, thank you! That raises the point about a [general naming for these "entities"](https://github.com/php/doc-en/pull/1732#issuecomment-1203771553). Would you have a suggestion?

Not really, I've been struggling with finding a generic name for these myself in other contexts. My current go-tos are "OO structures" or "classes and class-like structures".

Having said that, for the manual to be precise and spell things out is not necessarily a bad thing IMO>

**Comment by cmb69** [comment]
> Having said that, for the manual to be precise and spell things out is not necessarily a bad thing IMO.

I agree that in this case it is fine. There are other cases where that is "too" long, though.

**Comment by jrfnl** [comment]
> > Having said that, for the manual to be precise and spell things out is not necessarily a bad thing IMO.
> 
> I agree that in this case it is fine. There are other cases where that is "too" long, though.

Thanks and agreed. Will continue searching for an all-encompassing term for these structures, would be nice and useful terminology-wise to have such a term. Happy to brainstorm this out with others if more people are interested in solving this terminology conundrum.

**Pull request merged**
