### PR TITLE
Fixed Ticks usage example

### PR DESCRIPTION
**Pull request by AlexandrErohin**
There is a mistake in Tick usage example. There is `tick_handler();` after if clause - but it should not. The last tick event in the example is `print($a);`

### CODE REVIEW

**Comment by cmb69** [comment]
Ah, thanks, you're right. However, isn't the `if` a tick event? See https://3v4l.org/HUWGN.

**Comment by AlexandrErohin** [comment]
@cmb69 I thought, that it is working this way
https://3v4l.org/HUWGN
1) first tick event is - function call of register_tick_function
2) second tick event is print - print 1; Where function tick event occurs after execution of print
3) third tick event is print - print 2;
4) fourth tick event is print - print 3;
And according to https://www.php.net/manual/en/control-structures.declare.php
```
Not all statements are tickable. Typically, condition expressions and argument expressions are not tickable.
```
So I think `if` is not a tick event

**Comment by afilina** [comment]
I'm not sure I understand the purpose of the second example. If it was to highlight the occurrences of the tick event from the first example, then the comments on the first example would be sufficient, and the second example shouldn't be necessary.

**Comment by cmb69** [comment]
Oh, you're right! I think it's indeed best to drop the second example altogether.

**Comment by AlexandrErohin** [comment]
@cmb69 @afilina Good point! Thanks. I have deleted the second example and made the comments more clear

**Comment by cmb69** [comment]
Thank you! Now that part of the documentation finally makes sense.

I'm going to shorten the comments for better readability, though; at least the comment on the register_tick_function() call is likely to wrap, what doesn't look good.

**Pull request closed without merging**
