### PR TITLE
Generate ext/date methodsynopses based on stubs

### PR DESCRIPTION
**Pull request by kocsismate**

### CODE REVIEW

**Review by salathe — CHANGES_REQUESTED** [review]
Please don't remove the `role` attributes from the `*synopsis` elements. Those are used to decide what to include in the class synopses (for example, the list of methods for each class).

**Comment by cmb69** [comment]
Thanks @salathe! I completely missed [the xincludes](https://github.com/php/doc-base/blob/498fdd8f5425606ead8ad32dd0ff7df0b4b4c95f/RFC/skeletons/classname.xml#L69).

**Comment by kocsismate** [comment]
I've reintroduced the role generator capability of gen_stub.php. As there are a few edge case `role` values in this extension, I had to manually remove some unintended changes from the git change set.

**Comment by cmb69** [comment]
Thank you!

**Pull request closed without merging**
