### PR TITLE
Use updated parameter names for ldap_exop

### PR DESCRIPTION
**Pull request by othercorey**
I don't know if these ever get re-generated.

### CODE REVIEW

**Comment by cmb69** [comment]
It would be great if the changed parameter names are used throughout that manual page.

**Comment by cmb69** [comment]
And note that there is https://github.com/php/php-src/blob/master/build/gen_stub.php which supports which allows semi-automatic updates.

**Comment by othercorey** [comment]
> It would be great if the changed parameter names are used throughout that manual page.

Whoops, that was silly.

**Comment by othercorey** [comment]
@cmb69 Some of these ldap functions have a reference parameter like `&$controls` that defaults to null but isn't explicitly marked nullable. The same parameter is marked nullable most of the time when it's not a reference. Are references meant to only default to null but not use the nullable type declaration?

**Comment by cmb69** [comment]
> Are references meant to only default to null but not use the nullable type declaration?

Defaulting to `null` is more like a convention for reference parameters to show that they are optional. Actually, in this case they are out parameters, and only for that the type is relevant. Consider the following script which is correct:
````php
$output = "foo";
$status = [];
exec("dir", $output, $status);
````

**Pull request merged**
