### PR TITLE
Update parse-ini-string.xml

### PR DESCRIPTION
**Pull request by mowangjuanzi**
Unified with parse_ini_file

### CODE REVIEW

**Comment by cmb69** [comment]
While `[` may be [used in values](https://3v4l.org/FY1X1), I don't think it can be [used in keys](https://3v4l.org/TmnSp). We should clarify that.

**Comment by mowangjuanzi** [comment]
@cmb69 thanks for the reply.

Line [341](https://github.com/php/doc-en/blob/master/reference/filesystem/functions/parse-ini-file.xml#L341) in parse_ini_file.xml  

```xml
    Characters <literal>?{}|&amp;~!()^"</literal> must not be used anywhere in
    the key and have a special meaning in the value.
```

I understand that the processing mechanism of the parse_ini_file function and the parse_ini_string function should be the same.

So the description of parse_ini_file should be modified?

**Comment by cmb69** [comment]
> I understand that the processing mechanism of the parse_ini_file function and the parse_ini_string function should be the same.

Right. And so should the documentation. With regard to this issue (the `[`), neither man page is correct. :(

**Comment by mowangjuanzi** [comment]
OK, then I'll close the current PR. waiting for update.

**Pull request closed without merging**
