### PR TITLE
Show info about PHP error reporting

### PR DESCRIPTION
**Pull request by kestutisv**
Reader needs to be informed about PHP errors.

### CODE REVIEW

**Comment by cmb69** [comment]
Ah, thanks, good catch! We should note, though, that no error was raised [prior to PHP 7.1.0](https://3v4l.org/Q6j5M), and I'm also concerned regarding the line length (examples just wrap around); maybe move the comment about the errors *above* the "10 little piggies" line, and use multiple lines for it, and state that it applies to the following two lines?

**Review by cmb69 — CHANGES_REQUESTED** [review]
After having had a closer look, I think we should split that example (i.e. the last two statements). That could better incorporate the somewhat detached comment regarding these statements, so we don't have to add these comments to the example in the first place.

**Comment by afilina** [comment]
@kestutisv Pinging author.

**Comment by kamil-tekiela** [comment]
This page has been completely redesign in the meantime. This PR is now outdated. If the new page still needs adjusting, please raise a new PR.

**Pull request closed without merging**
