### PR TITLE
getiterator.xml Specify the exact classname for the new iterator

### PR DESCRIPTION
**Pull request by mmalferov**
Can we specify which iterator is created using this method? This will also link the method and the specific iterator

### CODE REVIEW

**Comment by cmb69** [comment]
[ArrayObject::__construct](https://www.php.net/manual/en/arrayobject.construct.php) allows to specify the iterator class (third parameter), so this is not necessarily `ArrayIterator` (unfortunately).

**Comment by mmalferov** [comment]
Yes, you're right, I've been thinking about it. Maybe like this?

`Create a new iterator (default is <classname>ArrayIterator</classname>) from an <classname>ArrayObject</classname> instance`.

**Comment by cmb69** [comment]
Maybe also mark up `<interfacename>Iterator</interfacename>`?

**Comment by mmalferov** [comment]
These links were missing. The ArrayObject and ArrayIterator class (along with the Iterator interface) lived separately 👍

**Comment by cmb69** [comment]
Thank you!

**Pull request merged**
