### PR TITLE
Generate intl methodsynopses - IntlDateFormatter

### PR DESCRIPTION
**Pull request by kocsismate**
As far as I saw, no notable change happened with this class

### CODE REVIEW

**Comment by cmb69** [comment]
There have been a few commits regarding the stubs recently; could you please check whether that would change anything?

**Comment by kocsismate** [comment]
> There have been a few commits regarding the stubs recently; could you please check whether that would change anything?

I've tried to search for some updated signatured - possibly I missed quite a few. Unfortunately, there's still more 1000 changed files if I generate the methodsynopses based on the whole `ext/` directory :(

**Comment by kocsismate** [comment]
Oh, I've just realized that you probably meant updates in connection with this PR. Just pushed one change!

**Comment by cmb69** [comment]
Yes, I was referring to this PR in particular. :)

**Comment by cmb69** [comment]
Thank you!

My favorite amendment of this PR (for `IntlDateFormatter::setTimezone()`):
````
Returns &null; on success and &false; on failure.
````
heh

**Pull request closed without merging**
