### PR TITLE
Remove redundant if and use short array syntax

### PR DESCRIPTION
**Pull request by kamil-tekiela**

### CODE REVIEW

**Review by cmb69 — COMMENTED** [review]
Thank you! I wonder whether we should add some info regarding error handling on this page ("the following examples assume ERRMODE_EXCEPTION" or "error handling omitted for brevity").

**Comment by kamil-tekiela** [comment]
I don't believe it's necessary. It's the default anyway. Besides, these examples are not self-contained and they don't show the connection part. Thus the error setting mode is also not shown.

**Comment by cmb69** [comment]
Well, ERRMODE_EXCEPTION is the default as of PHP 8.1.0, which is not even released. But okay, I agree that it's not necessary to mention the omitted error handling for these examples.

**Comment by kamil-tekiela** [comment]
It's the default as of PHP 8.0

**Pull request merged**
