### PR TITLE
Removed mysql extension

### PR DESCRIPTION
**Pull request by saundefined**
It seems like it's possible to remove the `mysql` extension, 
but I'm not sure 🤔

### CODE REVIEW

**Review by cmb69 — COMMENTED** [review]
I think it's a bit early. Unfortunately, this appears to still be widely used. Okay, there are the [legacy docs](https://php-legacy-docs.zend.com/manual/php5/en/index) now, but there is something [misconfigured on the server](https://marc.info/?l=phpdoc&m=161875795124552&w=2), so that the links to the legacy docs are not shown when searching.

**Comment by saundefined** [comment]
Ah.. got it.
Then I'll convert the PR into a draft, let it wait in the wings

**Comment by afilina** [comment]
@cmb69 Is there a plan to fix the nginx config for the 404s? This PR is accumulating merge conflicts. Alternatively, should we close this PR?

**Comment by saundefined** [comment]
@afilina I guess we can close the PR,
if the nginx problem is solved, it's easier to do that again from scratch

**Pull request closed without merging**
