### PR TITLE
mention is_a() is also working on interface class-strings

### PR DESCRIPTION
**Pull request by staabm**
see https://3v4l.org/HmGbd

### CODE REVIEW

**Comment by staabm** [comment]
thx for the feedback. what do you think about `class-like`?

**Comment by cmb69** [comment]
> phpparser considers also a Trait as a ClassLike, which would be confusing

Yeah. Additionally, "ClassLike" is not really a noun, but rather an adjective.

Further suggestions welcome! Maybe there are some native speakers around?

**Comment by staabm** [comment]
`class-string` just came to my mind

**Comment by Crell** [comment]
In context, the correct term would be "type", or maybe "object type".  That non-basic type is synonymous with object in PHP is incidental.

**Comment by staabm** [comment]
adjusted to 'type' per suggestion. thanks.

**Comment by cmb69** [comment]
I don't think "type" cuts it – we have a lengthy [section about types in the manual](https://www.php.net/types), and most of these types can't be used with `is_a()`. And I've just seen that the respective parameter of `is_a()` is called `$class`, so maybe we should leave the `<refpurpose>` alone, but (verbosly) clarify the description of the function and its parameters?

**Comment by Crell** [comment]
How about "object type", which limits it to typeable object thingies (classes, interfaces, enums, and if Records are ever added in the future probably them, too).

**Comment by cmb69** [comment]
I went with "object type". Thank you all!

**Pull request closed without merging**
