### PR TITLE
Clarify pseudo C preprocessor support

### PR DESCRIPTION
**Pull request by cmb69**
Based on a patch provided by Larry Garfield.

### CODE REVIEW

**Comment by Crell** [comment]
I wasn't quite sure how to file this information, frankly.  But I spent >2 days figuring out the path needs, so it seemed prudent to document it so that others don't have to waste 2 days on it.  I'm open to suggestions on how better to document these facts.

**Comment by Crell** [comment]
How do we move this forward?

**Comment by cmb69** [comment]
Thanks for the ping! In my opinion, the PR is okay (maybe wording could be improved; suggestions welcome!)

**Comment by nikic** [comment]
Possibly we can refer to https://www.php.net/manual/en/class.ffi.php, which explains what the scope stuff is for? The added note here doesn't really make it clear what it does, apart from the fact that you can use it.

**Comment by cmb69** [comment]
I fixed the broken PR, and added a commit with a link to the class intro.

**Comment by Crell** [comment]
Thanks, @cmb69!  I think this is ready for whoever does the magic from here.

**Comment by cmb69** [comment]
Thanks! Applied as http://svn.php.net/viewvc?view=revision&revision=349215.

**Pull request closed without merging**
