### PR TITLE
Add links to INI_* constants

### PR DESCRIPTION
**Pull request by haszi**
Replace XInclude'd variablelist with a duplicate which does not have any IDs for the constants. Add IDs to the variablelist on the constant page.

### CODE REVIEW

**Comment by Girgias** [comment]
The lack of support for XInclude 1.1 is really annoying....

**Comment by haszi** [comment]
> The lack of support for XInclude 1.1 is really annoying....

If only we had attribute copying or `set-xml-id` attribute support from 1.1... :-)

**Comment by haszi** [comment]
Even though this PR duplicates the table for the `INI_*` constants, I still think this makes sense as these are probably the most frequently used constants in the documentation. If there are no objections, I'd like to merge this around the end of next week.

**Comment by jimwins** [comment]
Maybe leave the xi:include in a comment and mention that once whatever tool in the process that needs to add XInclude support does, this section can be fixed?

**Comment by jimwins** [comment]
A breadcrumb for anyone interested in the future: it's `libxml2` that lacks XInclude 1.1 support, the spec is 8 years old, and the open issue for adding support in `libxml2` doesn't show any sign of interest: https://gitlab.gnome.org/GNOME/libxml2/-/issues/322

**Comment by haszi** [comment]
> Maybe leave the xi:include in a comment and mention that once whatever tool in the process that needs to add XInclude support does, this section can be fixed?

@jimwins Would the comment in my last commit work?

**Comment by jimwins** [comment]
@haszi Looks great, thanks!

**Review by Girgias — APPROVED** [review]

**Pull request merged**
