### PR TITLE
Fix minor typo in cloning.xml leading paragraph

### PR DESCRIPTION
**Pull request by xSavitar**
The leading paragraph didn't quite read well due to the typo. This  patch fixes it.

### CODE REVIEW

**Review by TimWolla — COMMENTED** [review]
I do not believe this change is correct. I believe "copy" is not a verb here and instead is part of the compound noun "copy constructor".

**Comment by xSavitar** [comment]
Compound nouns must be really interesting then :). It didn't quite read well to me, but if you say it's correct then that is fine. Thank you for reviewing.

Could you link me to some examples of how "copy" is used as a compound noun? Thanks!

**Comment by TimWolla** [comment]
> Could you link me to some examples of how "copy" is used as a compound noun? Thanks!

https://en.wikipedia.org/wiki/Copy_constructor_(C%2B%2B) is likely an appropriate reference for the concept.

**Comment by xSavitar** [comment]
> > Could you link me to some examples of how "copy" is used as a compound noun? Thanks!
> 
> https://en.wikipedia.org/wiki/Copy_constructor_(C%2B%2B) is likely an appropriate reference for the concept of a “copy constructor”.

Thank you very much!

**Pull request closed without merging**
