### PR TITLE
Fix parameter names for array functions

### PR DESCRIPTION
**Pull request by kalehmann**
After  #614 and #615 I realized, that the documentations uses different parameter names than the actual implementation for many functions. This is a huge problem with the [named arguments][1] from PHP8.

I have hacked together a script, that parses the parses the xml files of the documentation and compares the parameter names to the actual ones using reflection. This script is available in [this gist][2].

The following name differences were detected by the script for function under `reference/array`. As this table is **automatically generated**, some entries may be **wrong** or **missing** and all entries must be manually reviewed.

Function                                |Expected parameter name                 |Actual parameter name                   
----------------------------------------|----------------------------------------|----------------------------------------
array_diff_ukey                         |arrays                                  |rest                                    
array_diff_ukey                         |arrays                                  |rest                                    
array_diff_ukey                         |arrays                                  |rest                                    
array_intersect_uassoc                  |arrays                                  |rest                                    
array_intersect_uassoc                  |arrays                                  |rest                                    
array_intersect_uassoc                  |arrays                                  |rest                                    
array_intersect_ukey                    |arrays                                  |rest                                    
array_intersect_ukey                    |arrays                                  |rest                                    
array_intersect_ukey                    |arrays                                  |rest                                    
array_multisort                         |array1                                  |array                                   
array_multisort                         |array1_sort_order                       |rest                                    
array_multisort                         |array1                                  |array                                   
array_multisort                         |array1_sort_order                       |rest                                    
array_multisort                         |array1                                  |array                                   
array_multisort                         |array1_sort_order                       |rest                                    
array_udiff_assoc                       |arrays                                  |rest                                    
array_udiff_assoc                       |arrays                                  |rest                                    
array_udiff_assoc                       |arrays                                  |rest                                    
array_udiff_uassoc                      |arrays                                  |rest                                    
array_udiff_uassoc                      |arrays                                  |rest                                    
array_udiff_uassoc                      |arrays                                  |rest                                    
array_udiff                             |arrays                                  |rest                                    
array_udiff                             |arrays                                  |rest                                    
array_udiff                             |arrays                                  |rest                                    
array_uintersect_assoc                  |arrays                                  |rest                                    
array_uintersect_assoc                  |arrays                                  |rest                                    
array_uintersect_assoc                  |arrays                                  |rest                                    
array_uintersect_uassoc                 |array1                                  |array                                   
array_uintersect_uassoc                 |arrays                                  |rest                                    
array_uintersect_uassoc                 |array1                                  |array                                   
array_uintersect_uassoc                 |arrays                                  |rest                                    
array_uintersect_uassoc                 |array1                                  |array                                   
array_uintersect_uassoc                 |arrays                                  |rest                                    
array_uintersect                        |arrays                                  |rest                                    
array_uintersect                        |arrays                                  |rest                                    
array_uintersect                        |arrays                                  |rest                                    
array_walk_recursive                    |userdata                                |arg                                     
array_walk_recursive                    |userdata                                |arg                                     
array_walk_recursive                    |userdata                                |arg                                     
array_walk                              |userdata                                |arg                                     
array_walk                              |userdata                                |arg                                     
array_walk                              |userdata                                |arg               

  [1]: https://wiki.php.net/rfc/named_params
  [2]: https://gist.github.com/kalehmann/a175e7b60f7efc224201146deffe85eb

### CODE REVIEW

**Comment by Girgias** [comment]
We are aware of the issues, please proceed by doing extension by extension like all the other PRs as they are easier to review and might point to larger issues with the docs and/or problems with the stubs.

**Comment by kalehmann** [comment]
Okay, I have limited this PR to functions under 'reference/array'

**Comment by nikic** [comment]
See also #266.

**Comment by kalehmann** [comment]
> See also #266.

Thank you for pointing this out. I have decided to not bring `$rest` to the docs. However I still have changed `$userdata` to `$arg` for `array_walk` and `array_walk_recursive`

**Review by kamil-tekiela — APPROVED** [review]

**Comment by kamil-tekiela** [comment]
Thanks, I don't see a reason why this PR should not be merged now.

**Pull request merged**
