### PR TITLE
Add LDAP constants

### PR DESCRIPTION
**Pull request by haszi**
I did not write any descriptions for the peer certificate checking and CRL evaluation strategy constants as I could not find any references discussing these in detail.

Peer certificate checking strategies:
`LDAP_OPT_X_TLS_ALLOW`
`LDAP_OPT_X_TLS_DEMAND`
`LDAP_OPT_X_TLS_HARD`
`LDAP_OPT_X_TLS_NEVER`
`LDAP_OPT_X_TLS_TRY`

CRL evaluation strategies:
`LDAP_OPT_X_TLS_CRL_ALL`
`LDAP_OPT_X_TLS_CRL_NONE`
`LDAP_OPT_X_TLS_CRL_PEER`

### CODE REVIEW

**Comment by haszi** [comment]
I've found [this page](https://www.openldap.org/lists/openldap-software/200706/msg00173.html) where it is suggested that the `TLS_REQCERT` (and presumably the `TLS_CRLCHECK`) sections of [this manpage](https://linux.die.net/man/5/ldap.conf) are what we're looking for here. Unfortunately I don't know enough about LDAP to be sure.

**Comment by Girgias** [comment]
I'll wait a bit longer, if @MCMic doesn't reply we'll merge as is.

**Comment by haszi** [comment]
I've read up some more on LDAP and added the descriptions for peer certificate and CRL evaluation strategies.

References:
 - [client](https://linux.die.net/man/5/ldap.conf) (TLS_REQCERT and TLS_CRLCHECK)
 - [server](https://www.man7.org/linux/man-pages/man5/slapd.conf.5.html) (TLSVerifyClient and TLSCRLCheck)

**Comment by kocsismate** [comment]
@Girgias Do you think we can merge it now? If all LDAP constants are going to be documented then only ~170 globals constants remain undocumented (on the global constants page at least). That's brilliant work! 👏

**Comment by kocsismate** [comment]
> I'll wait a bit longer, if @MCMic doesn't reply we'll merge as is.

err: timeout ^^ i'm merging it

**Comment by Girgias** [comment]
Sorry, I've left docs on the way side to deal with other stuff that I found more enjoyable for a bit.

**Comment by MCMic** [comment]
Sorry about not responding here :bow: 
I do not know much about these options.

**Pull request merged**
