### PR TITLE
Update integer overflow example

### PR DESCRIPTION
**Pull request by wpdevelopment11**
I think this way it's more obvious what you're trying to show.

### CODE REVIEW

**Comment by cmb69** [comment]
It would say it's debatable what's more obvious. Another option would be to write `var_dump($large_number + 1);`.

**Comment by wpdevelopment11** [comment]
For me it's not immediately obvious that the second number differs only in one here:
```
$large_number = 2147483647;
var_dump($large_number);                     // int(2147483647)
$large_number = 2147483648;
var_dump($large_number);                     // float(2147483648)
$million = 1000000;
```

**Comment by cmb69** [comment]
I had a closer look: now we have two different examples (for 32bit and 64bit); it might make sense to have only one example, using `PHP_INT_MAX` and stating the results for 32bit/64bit in the comments. If we go this way, we can't specify any literal numbers, but would need to go with `+=` or `+ 1` anyway.

**Comment by wpdevelopment11** [comment]
Updated according to your comments.
I think that large literal is still useful to show that not only expressions are interpreted as floats, but literals too.
Moved the integer division example, I don't think that it's related to overflow.

**Comment by cmb69** [comment]
Thank you!

**Pull request merged**
