### PR TITLE
php memory stream can't be passed to library on Windows

### PR DESCRIPTION
**Pull request by Danack**
apparently.

e.g. fix needed for Imagick on windows: https://github.com/Imagick/imagick/pull/493

### CODE REVIEW

**Comment by cmb69** [comment]
Hmm, would it be possible to attempt such casts from userland? Otherwise I think this should be documented in some internal docs.

**Comment by Danack** [comment]
tbh, I don't really understand the underlying problem (and am fine not knowing) but the note should probably be on the user facing docs, as it seems like the type of thing that a windows user might encounter if an extension is maintained by someone who mostly uses Linux.

**Comment by cmb69** [comment]
> […] as it seems like the type of thing that a windows user might encounter if an extension is maintained by someone who mostly uses Linux.

Especially in this case, wouldn't it be good if the Windows user reported this issue to the maintainers, so they could fix the code (maybe by just reporting the problem explicitily)?

And generally, how would a Windows user even know where such cast to stdio might happen?

And of course, it would be nice if casting memory streams to stdio stream would also be supported on Windows. It *might* be possible to use a memory mapped temporary file for that, but I presume it's not generally possible. Anyway, that's a different story.

**Comment by afilina** [comment]
@cmb69 Is the text in this PR technically correct? Although these things can be documented internally, it may not hurt to have a mention here. Other people might end up on this page in search of information.

**Comment by cmb69** [comment]
Well, I'm still somewhat concerned about the `fopencookie()` mention. At the very least, we should clarify that this is a C function (not a PHP function). Not sure if readers would understand `fopencookie(3)`, or whether we should say `the C function fopencookie()`.

**Comment by afilina** [comment]
@Danack It looks like this is waiting on the author. Gently nudging.

**Pull request closed without merging**
